### ISSUE TITLE
Proposal to include information about the gas fee

### ISSUE THREAD

**Issue by cryshado** [dkeysil/awesome-ton-smart-contracts#1]
A lot of users ask how gas fees are charged in TON smart contracts. 
That's why I propose to include information about it in this repository.

Logical inference:

There is no point in calling `accept_message()` within the internal message, since the gas fees come with the TONs that came with the transaction. 

(Suggestion: if `accept_message()` in internal, it will allow to use the balance of the contract)

Within external message, the payment for gas only goes for transactions that change something in the blockchain(the rest is free). It need to call `accept_message()` after "all checks", before changing something in blockchain(like contract storage or for example `send_raw_message()`)

- please experienced people to correct me if i wrote something wrong

**Comment by akifoq** [comment]
`accept_message` simply sets the gas limit to the maximal possible value (the gas that can be bought by both original contract balance and message value, or, more commonly, the maximal gas amount allowed to use in single transaction) and also sets gas credit to zero.

In the case of external messages you need to accept the message in order to make transaction appear in the block (or, more precisely speaking, you need to somehow set gas credit to zero). You can accept message at any time during the TVM execution, even after calling `send_raw_message` primitive. The only way the fees may be charged from the account is to put a transaction into the blockchain, so it's the reason why "transactions" with no `accept_message` are "free".

In the case of internal messages the initial gas limit is set equal to the amount of gas that can be bought by message value. `accept_message` raises that limit. Even without `accept_message` you can spend more coins than the message value by sending some other messages which carry value.

**Comment by cryshado** [comment]
@akifoq  Then perhaps a good practice for internal messages would be to use [`set_gas_limit`](https://ton.org/docs/#/func/stdlib?id=set_gas_limit) to limit the charge for gas within the TON amount sent with the message. is it true? Or it still doesn't help to limit gas in the case of sending other messages that carry value?

**Comment by akifoq** [comment]
It doesn't help and the gas limit is by default set in such way. Gas fees are the fees on computation only. You can use small amount of gas, but send a message with large amount of coins. You can use `raw_reserve` in addition to gas limit to limit spendable amount of coins.

**Comment by cryshado** [comment]
@akifoq thanks for the detailed answer!
